<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Release</Configuration>
    <PlatformTarget Condition="'$(PlatformTarget)' == ''">x64</PlatformTarget>
    <OutputType>Exe</OutputType>
    <AssemblyName>Insomnia.Tests</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <OutputPath>bin\$(PlatformTarget)\</OutputPath>
    <IntermediateOutputPath>obj\$(PlatformTarget)\</IntermediateOutputPath>
    <WarningLevel>4</WarningLevel>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Configuration" />
    <Reference Include="Insomnia"><HintPath>..\artifacts\Release\Insomnia.exe</HintPath></Reference>
    <Compile Include="Tests.cs" />
    <None Include="App.config" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
