//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insomnia.Properties
{


    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static readonly Settings defaultInstance = (Settings)global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings());

        public static Settings Default { get { return defaultInstance; } }

        [global::System.Configuration.UserScopedSetting]
        [global::System.Configuration.DefaultSettingValue("True")]
        public bool ManuallyEnabled { get { return (bool)this["ManuallyEnabled"]; } set { this["ManuallyEnabled"] = value; } }

        [global::System.Configuration.UserScopedSetting]
        [global::System.Configuration.DefaultSettingValue("False")]
        public bool ScheduleEnabled { get { return (bool)this["ScheduleEnabled"]; } set { this["ScheduleEnabled"] = value; } }

        [global::System.Configuration.UserScopedSetting]
        [global::System.Configuration.DefaultSettingValue("08:00:00")]
        public global::System.TimeSpan ScheduleStart { get { return (global::System.TimeSpan)this["ScheduleStart"]; } set { this["ScheduleStart"] = value; } }

        [global::System.Configuration.UserScopedSetting]
        [global::System.Configuration.DefaultSettingValue("17:00:00")]
        public global::System.TimeSpan ScheduleEnd { get { return (global::System.TimeSpan)this["ScheduleEnd"]; } set { this["ScheduleEnd"] = value; } }

        [global::System.Configuration.UserScopedSetting]
        [global::System.Configuration.DefaultSettingValue("127")]
        public int ScheduleDays { get { return (int)this["ScheduleDays"]; } set { this["ScheduleDays"] = value; } }

        [global::System.Configuration.UserScopedSetting]
        [global::System.Configuration.DefaultSettingValue("0")]
        public int WifiMode { get { return (int)this["WifiMode"]; } set { this["WifiMode"] = value; } }

        [global::System.Configuration.UserScopedSetting]
        [global::System.Configuration.DefaultSettingValue("")]
        public global::System.Collections.Specialized.StringCollection ExcludedSsids { get { return (global::System.Collections.Specialized.StringCollection)this["ExcludedSsids"]; } set { this["ExcludedSsids"] = value; } }
    }
}
